name: Apex Tests

on:
  push:
    branches:
      - dev

jobs:
  apex-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate to DevSandbox
      run: echo ${{ secrets.DEV_SFDX_AUTH_URL }} | sfdx auth:sfdxurl:store --setalias DevSandbox

    - name: Run Apex Tests
      run: sfdx force:apex:test:run --resultformat human --wait 10 -u DevSandbox

    - name: Send Email on Apex Test Failure
      if: failure()
      run: |
        echo "Apex test failed!" | mail -s "Apex Test Failure" ${{ secrets.EMAIL_USERNAME }}
