name: Deploy to UAT

on:
  push:
    branches:
      - uat

jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate to UATSandbox
      run: echo ${{ secrets.UAT_SFDX_AUTH_URL }} | sfdx auth:sfdxurl:store --setalias UATSandbox

    - name: Deploy Metadata to UATSandbox
      run: sfdx force:source:deploy -p force-app/main/default -u UATSandbox --wait 10

    - name: Send Email on Deploy to UAT Failure
      if: failure()
      run: |
        echo "Deploy to UAT failed!" | mail -s "UAT Deployment Failure" ${{ secrets.EMAIL_USERNAME }}
