name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install --global @salesforce/cli

    - name: Authenticate to Production
      run: echo ${{ secrets.PROD_SFDX_AUTH_URL }} | sf auth:sfdxurl:store --alias Production

    - name: Deploy Metadata to Production
      run: sf project deploy start --source-dir force-app/main/default --target-org Production --wait 10

    - name: Send Email on Deploy to Prod Failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Deployment to Production Failed"
        to: padduja712@gmail.com
        from: ci-cd@yourcompany.com
        body: |
          🚨 Deployment to Production failed on branch ${{ github.ref }}.
          Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
