name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      uses: amtrack/sfdx-action@v1

    - name: Deploy Metadata to DevSandbox
      run: sfdx force:source:deploy -p force-app -u DevSandbox --wait 10
