name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate to Production
      run: echo ${{ secrets.PROD_SFDX_AUTH_URL }} | sfdx auth:sfdxurl:store --setalias ProdOrg

    - name: Deploy Metadata to Production
      run: sfdx force:source:deploy -p force-app/main/default -u ProdOrg --wait 10

    - name: Send Email on Deploy to Production Failure
      if: failure()
      run: |
        echo "Deploy to Production failed!" | mail -s "Production Deployment Failure" ${{ secrets.EMAIL_USERNAME }}
