name: Deploy to UAT

on:
  push:
    branches:
      - uat

jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      uses: amtrack/sfdx-action@v1

    - name: Deploy Metadata to UATSandbox
      run: sfdx force:source:deploy -p force-app -u UATSandbox --wait 10
