name: Validation

on:
  push:
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate to DevSandbox
      run: echo ${{ secrets.DEV_SFDX_AUTH_URL }} | sfdx auth:sfdxurl:store --setalias DevSandbox

    - name: Validate Metadata
      run: sfdx force:source:deploy -p force-app/main/default -u DevSandbox --checkonly --json --wait 10

    - name: Send Email on Validation Failure
      if: failure()
      run: |
        echo "Validation failed!" | mail -s "Validation Failure" ${{ secrets.EMAIL_USERNAME }}
